/*
 * SimulationFrame.ts
 * author: evan kirkiles
 * created on Sat Jun 25 2022
 * 2022 the player space,
 */

export class SimulationFrame<T> {
  public position: T;
  public velocity: T;

  /**
   * Holds a single frame generated by a simulator
   * @param position The position calculated by the simulator
   * @param velocity The velocity calculated by the simulator
   */
  constructor(position: T, velocity: T) {
    this.position = position;
    this.velocity = velocity;
  }
}
